// 分類完全照 Apple 台灣官網頂部導覽（順序也一致）
export type Category = "mac" | "ipad" | "iphone" | "watch" | "vision" | "airpods" | "tvhome" | "accessories";
export type Verdict = "buy" | "wait" | "care" | "no" | "soon" | "disc";
export type Grade = "A" | "B" | "C";

export interface Signal {
  grade: Grade;
  text: string;
  source: string;
  date: string; // YYYY-MM-DD
}

// 已發表、台灣尚未開賣的新款。台灣開賣後：移進 releasedTW／prev／history，並刪掉 announced。
export interface Announced {
  name: string; // 新款名稱
  date: string; // 全球發表日 YYYY-MM-DD
  twRelease: string | null; // 台灣開賣日；未公布 = null
  source: string; // 來源（如 Apple Newsroom）
  url?: string; // 來源連結
}

/** Apple 台灣官網售價（一般售價，非教育價）。只放官網價，不放通路價。 */
export interface PriceTW {
  from: number; // 起售價（新台幣）
  config: string; // 起價對應的規格，例如「128GB」「11 吋 128GB」
  variants?: { label: string; price: number }[]; // 其他主要版本（選填）
  url: string; // 官網購買頁
  checked: string; // 查價日期 YYYY-MM-DD
}

export interface Product {
  slug: string;
  name: string;
  category: Category;
  icon: string; // components/Icons.tsx DeviceIcon 的 kind（自繪剪影，全站統一風格，不用照片）
  releasedTW: string; // 台灣開賣日 YYYY-MM-DD：台灣第一天可正式購買（預購不算；NCC 延後的 Mac／iPad 以官網開放訂購日為準）；未來日期 = 即將開賣
  avgDays: number | null; // 歷代平均更新天數，一律以美國首發日計算（避免台灣延後上市造成失真）；首代為 null
  prev: { name: string; date: string } | null; // 上一代
  next: { name: string; expected: string | null; grade: Grade | null; note: string }; // 下一代
  announced?: Announced; // 新款已發表但台灣尚未開賣時填寫
  priceTW?: PriceTW; // Apple 台灣官網售價
  twAvailable: boolean;
  discontinued?: string; // 停產日
  override?: { verdict: Verdict; reason: string };
  summary: string; // 一句話結論
  reasons: string[];
  signals: Signal[];
  specAdvice: { label: string; text: string }[];
  history: { gen: string; date: string }[]; // 歷代台灣開賣日，新到舊
}

export const CATEGORY_LABEL: Record<Category, string> = {
  mac: "Mac",
  ipad: "iPad",
  iphone: "iPhone",
  watch: "Watch",
  vision: "Vision",
  airpods: "AirPods",
  tvhome: "TV 和家庭",
  accessories: "配件",
};

export const PRODUCTS: Product[] = [
  {
    slug: "macbook-neo",
    name: "MacBook Neo（A18 Pro）",
    category: "mac",
    icon: "laptop",
    releasedTW: "2026-04-13",
    avgDays: null,
    prev: null,
    next: { name: "MacBook Neo（第二代）", expected: null, grade: "B", note: "Bloomberg 報導 2027 年推出，升級 A19 Pro、12GB 記憶體" },
    priceTW: { from: 22900, config: "256GB", variants: [{ label: "512GB", price: 25900 }], url: "https://www.apple.com/tw/shop/buy-mac/macbook-neo", checked: "2026-10-03" },
    twAvailable: true,
    summary: "今年 4 月才在台灣開賣的全新入門筆電，第二代要到 2027 年，需要就可以買。",
    reasons: ["台灣 2026-04-13 開賣，是第一代，也是第一款用 A 系列晶片的 Mac。", "Bloomberg 報導第二代 2027 年才推出。"],
    signals: [
      { grade: "B", text: "Gurman：第二代 MacBook Neo 升級 A19 Pro、12GB 記憶體與新顏色，2027 年推出。", source: "Bloomberg／MacRumors", date: "2026-09-04" },
    ],
    specAdvice: [{ label: "容量", text: "[編輯建議：256GB 與 512GB 取捨]" }],
    history: [{ gen: "MacBook Neo（A18 Pro）", date: "2026-04-13" }],
  },
  {
    slug: "macbook-air",
    name: "MacBook Air（M5）",
    category: "mac",
    icon: "laptop",
    releasedTW: "2026-04-13",
    avgDays: 366,
    prev: { name: "MacBook Air（M4）", date: "2025-04-14" },
    next: { name: "MacBook Air（M6）", expected: "2027-03-15", grade: "B", note: "多家媒體報導 2027 年初推出、外觀不變；日期為推估，台灣近年晚約 1 個月" },
    priceTW: { from: 42900, config: "13 吋 16GB／512GB", variants: [{ label: "15 吋 16GB／512GB", price: 49900 }], url: "https://www.apple.com/tw/shop/buy-mac/macbook-air", checked: "2026-10-03" },
    twAvailable: true,
    summary: "週期中段，M6 版傳聞 2027 年初推出，有需要就買。",
    reasons: ["台灣 4/13 開賣，週期進度約五成。", "Back to School 2026 已於 9/24 結束，目前只剩常態教育價。"],
    signals: [
      { grade: "B", text: "M6 MacBook Air 預計 2027 年初推出，外觀不變；OLED 版傳聞 2028 年。", source: "9to5Mac／MacRumors", date: "2026-09-30" },
    ],
    specAdvice: [
      { label: "記憶體", text: "[編輯建議：16GB 起跳是否足夠]" },
      { label: "教育價", text: "[編輯建議：教育商店價差]" },
    ],
    history: [
      { gen: "MacBook Air（M5）", date: "2026-04-13" },
      { gen: "MacBook Air（M4）", date: "2025-04-14" },
      { gen: "MacBook Air（M3）", date: "2024-04-11" },
    ],
  },
  {
    slug: "macbook-pro",
    name: "MacBook Pro（M5 Pro／Max）",
    category: "mac",
    icon: "laptop-pro",
    releasedTW: "2026-04-13",
    avgDays: 285,
    prev: { name: "MacBook Pro（M5）", date: "2025-11-20" },
    next: { name: "MacBook Pro（M6，14 吋基本款）", expected: "2026-10-31", grade: "B", note: "Bloomberg 報導 M6 基本款與 OLED 觸控高階款都可能 10–11 月推出（美國）；台灣可能晚 1 個月以上" },
    priceTW: { from: 64900, config: "14 吋 M5 16GB／1TB", variants: [{ label: "14 吋 M5 Pro", price: 84900 }, { label: "16 吋 M5 Pro", price: 99900 }, { label: "14 吋 M5 Max", price: 139900 }], url: "https://www.apple.com/tw/shop/buy-mac/macbook-pro", checked: "2026-10-03" },
    twAvailable: true,
    summary: "M6 基本款與 OLED 觸控螢幕高階款都傳 10–11 月推出，不管買哪一款都建議先等等。",
    reasons: ["Bloomberg 報導 M6 基本款預計 10 月推出（B 級訊號）。", "Gurman 10/1 表示 OLED 觸控螢幕的 14、16 吋高階款（M5 Pro／Max）最快 10 月、可能 11 月推出。"],
    signals: [
      { grade: "B", text: "macOS 27.2 測試版 3 新增 Dock 圖示長按放大動畫，和 iPhone／iPad 的觸控操作一樣，觸控 MacBook 跡象更明顯。", source: "MacRumors", date: "2026-10-06" },
      { grade: "C", text: "macOS 27.2 測試版 3 加入多個 app 的觸控手勢程式碼，可能是為 OLED 觸控 MacBook 準備，但也可能只是 iPad 並行（Sidecar）功能。", source: "MacRumors（程式碼分析）", date: "2026-10-05" },
      { grade: "B", text: "Gurman：首款 OLED 觸控螢幕 MacBook Pro（14、16 吋，M5 Pro／M5 Max）今年秋天推出，最快 10 月，可能延到 11 月。", source: "Bloomberg Power On／MacRumors", date: "2026-10-01" },
      { grade: "B", text: "Bloomberg（Gurman）報導 M6 版 14 吋 MacBook Pro 基本款預計 10 月推出，M6 不會有 Pro／Max 版。", source: "Bloomberg／MacRumors", date: "2026-08-25" },
      { grade: "B", text: "M6 MacBook Pro 預計秋季、可能 10 月或 11 月初推出。", source: "9to5Mac", date: "2026-09-30" },
    ],
    specAdvice: [
      { label: "晶片", text: "[編輯建議：Pro / Max 選擇]" },
      { label: "尺寸", text: "[編輯建議：14 吋與 16 吋]" },
    ],
    history: [
      { gen: "MacBook Pro（M5 Pro／Max）", date: "2026-04-13" },
      { gen: "MacBook Pro（M5）", date: "2025-11-20" },
      { gen: "MacBook Pro（M4）", date: "2024-12-05" },
      { gen: "MacBook Pro（M3）", date: "2023-12-05" },
    ],
  },
  {
    slug: "imac",
    name: "iMac（M4）",
    category: "mac",
    icon: "imac",
    releasedTW: "2024-12-05",
    avgDays: 634,
    prev: { name: "iMac（M3）", date: "2023-12-05" },
    next: { name: "iMac（M6）", expected: "2026-10-15", grade: "B", note: "Bloomberg 報導跳過 M5，M6 iMac 10 月或 11 月初推出；日期為推估" },
    priceTW: { from: 49900, config: "8 核心 CPU 16GB／256GB", variants: [{ label: "10 核心 CPU", price: 57900 }], url: "https://www.apple.com/tw/shop/buy-mac/imac", checked: "2026-10-03" },
    twAvailable: true,
    summary: "M4 iMac 在台灣已賣快兩年，Bloomberg 報導 M6 iMac 最快這個月發表，不急建議先等等。",
    reasons: ["台灣 2024-12-05 開賣，已超過歷代平均更新週期。", "Bloomberg 報導 M6 iMac 預計 10 月或 11 月初推出（B 級訊號）。"],
    signals: [
      { grade: "B", text: "Gurman：M6 iMac 年底前推出、會有新顏色。", source: "Bloomberg／MacRumors", date: "2026-08-23" },
      { grade: "B", text: "M6 MacBook Pro 與 iMac 預計秋季推出，最可能 10 月或 11 月初。", source: "9to5Mac", date: "2026-09-30" },
    ],
    specAdvice: [{ label: "配置", text: "[編輯建議：連接埠數量與顏色]" }],
    history: [
      { gen: "iMac（M4）", date: "2024-12-05" },
      { gen: "iMac（M3）", date: "2023-12-05" },
      { gen: "iMac（M1）", date: "2021-06-02" },
    ],
  },
  {
    slug: "mac-mini",
    name: "Mac mini（M6／M5 Pro）",
    category: "mac",
    icon: "mac-mini",
    releasedTW: "2026-09-22",
    avgDays: 668,
    prev: { name: "Mac mini（M4）", date: "2024-12-05" },
    next: { name: "Mac mini", expected: null, grade: null, note: "尚無訊號" },
    priceTW: { from: 29900, config: "M6 16GB／256GB", variants: [{ label: "M5 Pro 24GB／512GB", price: 59900 }], url: "https://www.apple.com/tw/shop/buy-mac/mac-mini", checked: "2026-10-03" },
    twAvailable: true,
    summary: "剛更新，離下一代最遠。",
    reasons: ["台灣 9/22 開賣，至今不到兩週。", "Mac mini 平均約 22 個月更新一次。"],
    signals: [],
    specAdvice: [{ label: "記憶體", text: "[編輯建議：後續無法升級，一次買足]" }],
    history: [
      { gen: "Mac mini（M6／M5 Pro）", date: "2026-09-22" },
      { gen: "Mac mini（M4）", date: "2024-12-05" },
      { gen: "Mac mini（M2）", date: "2023-03-14" },
    ],
  },
  {
    slug: "mac-studio",
    name: "Mac Studio（M5 Max／M5 Ultra）",
    category: "mac",
    icon: "mac-studio",
    releasedTW: "2026-09-22",
    avgDays: 550,
    prev: { name: "Mac Studio（M4 Max／M3 Ultra）", date: "2025-04-14" },
    next: { name: "Mac Studio（M7 Ultra）", expected: null, grade: "B", note: "Bloomberg 報導跳過 M6 Ultra，下一代 M7 Ultra 約 2028 年" },
    priceTW: { from: 84900, config: "M5 Max 36GB／512GB", variants: [{ label: "M5 Ultra 96GB／1TB", price: 199900 }], url: "https://www.apple.com/tw/shop/buy-mac/mac-studio", checked: "2026-10-03" },
    twAvailable: true,
    summary: "剛更新，離下一代最遠。",
    reasons: ["台灣 9/22 開賣，至今不到兩週；512GB 統一記憶體款 10 月底推出。", "Bloomberg 報導下一代要到 2028 年的 M7 Ultra。"],
    signals: [
      { grade: "B", text: "Gurman：Apple 跳過 M6 Ultra，Mac Studio 下一代 M7 Ultra 約 2028 年。", source: "Bloomberg／AppleInsider", date: "2026-06-28" },
      { grade: "B", text: "Gurman：Apple 跳過 M6 Pro／M6 Max，直接推 M7 Pro／Max。", source: "Bloomberg／MacRumors", date: "2026-07-12" },
    ],
    specAdvice: [{ label: "晶片", text: "[編輯建議：M5 Max 與 M5 Ultra 取捨、統一記憶體容量]" }],
    history: [
      { gen: "Mac Studio（M5 Max／M5 Ultra）", date: "2026-09-22" },
      { gen: "Mac Studio（M4 Max／M3 Ultra）", date: "2025-04-14" },
      { gen: "Mac Studio（M2 Max／M2 Ultra）", date: "2023-07-12" },
      { gen: "Mac Studio（M1 Max／M1 Ultra）", date: "2022-04-25" },
    ],
  },
  {
    slug: "studio-display",
    name: "Studio Display（2026）",
    category: "mac",
    icon: "display",
    releasedTW: "2026-03-20",
    avgDays: 1454,
    prev: { name: "Studio Display（2022）", date: "2022-04-18" },
    next: { name: "Studio Display", expected: null, grade: null, note: "尚無訊號" },
    priceTW: { from: 52900, config: "標準玻璃", variants: [{ label: "奈米紋理玻璃", price: 62900 }], url: "https://www.apple.com/tw/shop/buy-mac/studio-display", checked: "2026-10-03" },
    twAvailable: true,
    summary: "剛更新不久，顯示器更新週期長，可以買。",
    reasons: ["週期進度不到兩成。", "上一代相隔約四年才更新。"],
    signals: [],
    specAdvice: [{ label: "玻璃", text: "[編輯建議：標準與奈米紋理玻璃]" }],
    history: [
      { gen: "Studio Display（2026）", date: "2026-03-20" },
      { gen: "Studio Display（2022）", date: "2022-04-18" },
    ],
  },
  {
    slug: "studio-display-xdr",
    name: "Studio Display XDR",
    category: "mac",
    icon: "display-xdr",
    releasedTW: "2026-03-20",
    avgDays: 2283,
    prev: { name: "Pro Display XDR", date: "2019-12-11" },
    next: { name: "Studio Display XDR", expected: null, grade: null, note: "尚無訊號" },
    priceTW: { from: 107900, config: "奈米紋理玻璃＋VESA 吊架", variants: [{ label: "標準玻璃＋可調高度支架", price: 109900 }], url: "https://www.apple.com/tw/shop/buy-mac/studio-display-xdr", checked: "2026-10-03" },
    twAvailable: true,
    summary: "2026 年剛取代 Pro Display XDR，更新週期很長，可以買。",
    reasons: ["台灣 2026-03-20 開賣，週期進度不到一成。", "上一代 Pro Display XDR 賣了 6 年多才更新。"],
    signals: [],
    specAdvice: [{ label: "支架", text: "[編輯建議：VESA 版與支架版]" }],
    history: [
      { gen: "Studio Display XDR", date: "2026-03-20" },
      { gen: "Pro Display XDR", date: "2019-12-11" },
    ],
  },
  {
    slug: "ipad-pro",
    name: "iPad Pro（M5）",
    category: "ipad",
    icon: "tablet",
    releasedTW: "2025-11-20",
    avgDays: 546,
    prev: { name: "iPad Pro（M4）", date: "2024-06-13" },
    next: { name: "iPad Pro（M6）", expected: "2027-03-15", grade: "B", note: "Bloomberg 報導 2027 年春季推出、加均熱板散熱；日期為推估" },
    priceTW: { from: 39900, config: "11 吋 256GB Wi-Fi", variants: [{ label: "13 吋 256GB", price: 50900 }], url: "https://www.apple.com/tw/shop/buy-ipad/ipad-pro", checked: "2026-10-03" },
    twAvailable: true,
    summary: "M5 iPad Pro 在台灣上市快一年，新款要到明年春天，急用可以買，不急可以再等等。",
    reasons: ["台灣 2025-11-20 開賣，週期進度約六成。", "Bloomberg 報導下一代 M6 版要到 2027 年春季。"],
    signals: [
      { grade: "B", text: "Gurman：下一代 iPad Pro 2027 年春季推出，搭載 M6 與均熱板。", source: "Bloomberg／AppleInsider", date: "2026-03-01" },
      { grade: "B", text: "M5 iPad Pro 預計 2027 年前不會更新。", source: "9to5Mac", date: "2026-06-03" },
    ],
    specAdvice: [{ label: "尺寸", text: "[編輯建議：11 吋與 13 吋取捨]" }],
    history: [
      { gen: "iPad Pro（M5）", date: "2025-11-20" },
      { gen: "iPad Pro（M4）", date: "2024-06-13" },
      { gen: "iPad Pro（M2）", date: "2022-11-22" },
    ],
  },
  {
    slug: "ipad-air",
    name: "iPad Air（M4）",
    category: "ipad",
    icon: "tablet",
    releasedTW: "2026-03-24",
    avgDays: 332,
    prev: { name: "iPad Air（M3）", date: "2025-04-11" },
    next: { name: "iPad Air（M5）", expected: "2027-03-15", grade: "B", note: "Bloomberg 報導 2027 年春季推出、可能改 OLED；日期為推估，台灣通常晚 2–4 週" },
    priceTW: { from: 24900, config: "11 吋 128GB Wi-Fi", variants: [{ label: "13 吋 128GB", price: 31900 }], url: "https://www.apple.com/tw/shop/buy-ipad/ipad-air", checked: "2026-10-03" },
    twAvailable: true,
    summary: "週期過半，M5 版傳聞 2027 年春季推出；不急可等，有需要就買。",
    reasons: ["台灣 3/24 開賣，週期進度約六成。", "Bloomberg 報導下一代搭載 M5、2027 年春季推出（B 級訊號）。"],
    signals: [
      { grade: "B", text: "Bloomberg 報導下一代 iPad Air 搭載 M5，預計 2027 年春季推出，可能改用 OLED。", source: "Bloomberg／AppleInsider", date: "2026-07-16" },
    ],
    specAdvice: [
      { label: "尺寸", text: "[編輯建議：11 吋與 13 吋取捨]" },
      { label: "配件", text: "[編輯建議：Apple Pencil 與鍵盤相容]" },
    ],
    history: [
      { gen: "iPad Air（M4）", date: "2026-03-24" },
      { gen: "iPad Air（M3）", date: "2025-04-11" },
      { gen: "iPad Air（M2）", date: "2024-06-13" },
    ],
  },
  {
    slug: "ipad",
    name: "iPad（A16）",
    category: "ipad",
    icon: "tablet",
    releasedTW: "2025-04-11",
    avgDays: 633,
    prev: { name: "iPad（第 10 代）", date: "2022-11-22" },
    next: { name: "iPad（A19）", expected: "2027-03-15", grade: "B", note: "Apple 程式碼出現 A19 新款，媒體預期 2027 年春季推出；日期為推估" },
    priceTW: { from: 14900, config: "128GB Wi-Fi", variants: [{ label: "256GB", price: 18400 }], url: "https://www.apple.com/tw/shop/buy-ipad/ipad", checked: "2026-10-03" },
    twAvailable: true,
    summary: "這台入門 iPad 已上市一年半，新款已在 Apple 程式碼中現身、預計明年春天推出，不急建議等等。",
    reasons: ["台灣 2025-04-11 開賣，已走完平均週期約八成五。", "Apple 程式碼顯示下一代換 A19 晶片並支援 Apple Intelligence。"],
    signals: [
      { grade: "B", text: "Apple 程式碼顯示新入門 iPad 搭載 A19、8GB 記憶體，預期 2027 年春季推出。", source: "MacRumors／AppleInsider", date: "2026-09-25" },
      { grade: "B", text: "Gurman 曾稱新入門 iPad 在 2026 上半年推出，後來延期。", source: "9to5Mac", date: "2026-03-22" },
    ],
    specAdvice: [{ label: "容量", text: "[編輯建議：容量與行動網路版]" }],
    history: [
      { gen: "iPad（A16）", date: "2025-04-11" },
      { gen: "iPad（第 10 代）", date: "2022-11-22" },
      { gen: "iPad（第 9 代）", date: "2021-10-22" },
    ],
  },
  {
    slug: "ipad-mini",
    name: "iPad mini（A17 Pro）",
    category: "ipad",
    icon: "tablet-mini",
    releasedTW: "2024-11-20",
    avgDays: 1023,
    prev: { name: "iPad mini（第 6 代）", date: "2021-10-22" },
    next: { name: "iPad mini（A20 Pro）", expected: "2026-10-15", grade: "A", note: "Apple 程式碼與官方圖檔已出現新款；Bloomberg 報導 10 月底前在美國開賣，台灣通常晚約一個月" },
    priceTW: { from: 19900, config: "128GB Wi-Fi", variants: [{ label: "256GB", price: 23400 }], url: "https://www.apple.com/tw/shop/buy-ipad/ipad-mini", checked: "2026-10-03" },
    twAvailable: true,
    summary: "新一代 iPad mini 已在 Apple 程式碼中曝光，預計這個月就會發表，先別買舊款。",
    reasons: ["Apple 程式碼與官方產品圖中已出現新 iPad mini（A20 Pro 晶片）。", "Bloomberg 報導新款 10 月底前在美國開賣，台灣通常晚約一個月。"],
    signals: [
      { grade: "A", text: "Apple 程式碼與官方圖檔曝光新 iPad mini：A20 Pro、橫向前鏡頭、新揚聲器。", source: "MacRumors", date: "2026-09-25" },
      { grade: "B", text: "Gurman：新 iPad mini 將在 10 月底前推出。", source: "Bloomberg／MacRumors", date: "2026-08-24" },
    ],
    specAdvice: [{ label: "容量", text: "[編輯建議：容量與行動網路版]" }],
    history: [
      { gen: "iPad mini（A17 Pro）", date: "2024-11-20" },
      { gen: "iPad mini（第 6 代）", date: "2021-10-22" },
      { gen: "iPad mini（第 5 代）", date: "2019-05-08" },
    ],
  },
  {
    slug: "iphone-duo",
    name: "iPhone Duo",
    category: "iphone",
    icon: "phone-fold",
    releasedTW: "2026-10-23",
    avgDays: null,
    prev: null,
    next: { name: "iPhone Duo", expected: null, grade: null, note: "尚無訊號" },
    announced: { name: "iPhone Duo", date: "2026-09-09", twRelease: "2026-10-23", source: "Apple 台灣新聞稿", url: "https://www.apple.com/tw/newsroom/2026/09/apple-unveils-iphone-duo/" },
    priceTW: { from: 74900, config: "256GB", variants: [{ label: "512GB", price: 81900 }], url: "https://www.apple.com/tw/shop/buy-iphone/iphone-duo", checked: "2026-10-03" },
    twAvailable: true,
    summary: "首款折疊 iPhone，台灣 10/16 晚上 8 點開放預購、10/23 開賣。",
    reasons: ["9/9 與 iPhone 18 Pro 同場發表，台灣在首波開賣地區。", "台灣 10/16 晚上 8 點開放預購，10/23 開始供貨。"],
    signals: [],
    specAdvice: [{ label: "容量", text: "[編輯建議：依台灣售價級距與常見用途填入]" }],
    history: [{ gen: "iPhone Duo", date: "2026-10-23" }],
  },
  {
    slug: "iphone-18-pro",
    name: "iPhone 18 Pro／Pro Max",
    category: "iphone",
    icon: "phone",
    releasedTW: "2026-09-18",
    avgDays: 366,
    prev: { name: "iPhone 17 Pro", date: "2025-09-19" },
    next: { name: "iPhone 20 Pro（暫名）", expected: "2027-09-17", grade: "A", note: "依歷年規律推估 2027 年 9 月；傳聞跳過 19 直接命名 20，未經證實" },
    priceTW: { from: 44900, config: "iPhone 18 Pro 256GB", variants: [{ label: "iPhone 18 Pro Max 256GB", price: 49900 }], url: "https://www.apple.com/tw/shop/buy-iphone/iphone-18-pro", checked: "2026-10-03" },
    twAvailable: true,
    summary: "剛於 9 月換代，距離下一代預期發表還有約 11 個月，是整個週期裡最划算的時間點。",
    reasons: [
      "台灣 9/18 開賣，至今約兩週，遠低於「可以買」門檻的 30% 週期進度。",
      "Pro 系列自 13 Pro 起連續 6 代於 9 月發表，平均間隔約 366 天。",
    ],
    signals: [
      { grade: "A", text: "歷代規律：Pro 系列自 13 Pro 起連續 6 代於 9 月發表（12 Pro 因疫情延至 10 月），下一代最可能為 2027 年 9 月。", source: "本站歷代紀錄", date: "2026-10-02" },
      { grade: "B", text: "多方報導 2027 年機種可能跳號命名為 iPhone 20 Pro。", source: "MacRumors", date: "2026-09-21" },
    ],
    specAdvice: [
      { label: "容量", text: "[編輯建議：依台灣售價級距與常見用途填入]" },
      { label: "Pro / Max", text: "[編輯建議：螢幕尺寸與電池差異]" },
      { label: "公司貨", text: "公司貨享台灣保固與 NCC 認證；水貨價差請與保固風險一併評估。" },
    ],
    history: [
      { gen: "iPhone 18 Pro", date: "2026-09-18" },
      { gen: "iPhone 17 Pro", date: "2025-09-19" },
      { gen: "iPhone 16 Pro", date: "2024-09-20" },
      { gen: "iPhone 15 Pro", date: "2023-09-22" },
      { gen: "iPhone 14 Pro", date: "2022-09-16" },
    ],
  },
  {
    slug: "iphone-air",
    name: "iPhone Air",
    category: "iphone",
    icon: "phone-air",
    releasedTW: "2025-09-19",
    avgDays: null,
    prev: null,
    next: { name: "iPhone Air 2", expected: "2027-03-15", grade: "B", note: "Bloomberg 報導 2027 年上半年推出、改雙鏡頭；日期為推估" },
    priceTW: { from: 39900, config: "256GB", variants: [{ label: "512GB", price: 46900 }], url: "https://www.apple.com/tw/shop/buy-iphone/iphone-air", checked: "2026-10-03" },
    twAvailable: true,
    summary: "第一代已賣一年，第二代傳 2027 年上半年推出、改雙鏡頭，不急可等。",
    reasons: ["台灣 2025-09-19 開賣，是第一代。", "Bloomberg 報導 iPhone Air 2 將在 2027 年上半年推出，加上超廣角鏡頭。"],
    signals: [
      { grade: "B", text: "Gurman：iPhone Air 2 改用雙鏡頭，2027 年上半年與數字版 iPhone 18 一起推出。", source: "Bloomberg／TechSpot", date: "2026-09-15" },
      { grade: "B", text: "iPhone Air 2 與 iPhone 18e 預計明年初推出。", source: "MacRumors", date: "2026-04-08" },
    ],
    specAdvice: [{ label: "取捨", text: "[編輯建議：輕薄與電池、單鏡頭的取捨]" }],
    history: [{ gen: "iPhone Air", date: "2025-09-19" }],
  },
  {
    slug: "iphone",
    name: "iPhone 17",
    category: "iphone",
    icon: "phone",
    releasedTW: "2025-09-19",
    avgDays: 366,
    prev: { name: "iPhone 16", date: "2024-09-20" },
    next: { name: "iPhone 18", expected: "2027-03-15", grade: "B", note: "Bloomberg 報導數字版改到 2027 年上半年推出；日期為推估" },
    priceTW: { from: 32900, config: "256GB", variants: [{ label: "512GB", price: 39900 }], url: "https://www.apple.com/tw/shop/buy-iphone/iphone-17", checked: "2026-10-03" },
    twAvailable: true,
    summary: "已賣滿一年，iPhone 18 改到 2027 年上半年推出，急用可買、不急可等。",
    reasons: ["台灣 2025-09-19 開賣，已超過一年。", "Bloomberg 報導數字版 iPhone 18 不在今年 9 月推出，改到 2027 年上半年。"],
    signals: [
      { grade: "B", text: "Gurman：數字版 iPhone 18、iPhone Air 2、iPhone 18e 都在 2027 年上半年推出。", source: "Bloomberg／TechSpot", date: "2026-09-15" },
    ],
    specAdvice: [{ label: "容量", text: "[編輯建議：依台灣售價級距與常見用途填入]" }],
    history: [
      { gen: "iPhone 17", date: "2025-09-19" },
      { gen: "iPhone 16", date: "2024-09-20" },
      { gen: "iPhone 15", date: "2023-09-22" },
      { gen: "iPhone 14", date: "2022-09-16" },
    ],
  },
  {
    slug: "iphone-17e",
    name: "iPhone 17e",
    category: "iphone",
    icon: "phone",
    releasedTW: "2026-03-11",
    avgDays: 376,
    prev: { name: "iPhone 16e", date: "2025-02-28" },
    next: { name: "iPhone 18e", expected: "2027-03-15", grade: "B", note: "Bloomberg 報導 2027 年春季推出，主要升級晶片；日期為推估" },
    priceTW: { from: 25900, config: "256GB", variants: [{ label: "512GB", price: 32900 }], url: "https://www.apple.com/tw/shop/buy-iphone/iphone-17e", checked: "2026-10-03" },
    twAvailable: true,
    summary: "下一代 iPhone 18e 預計明年春天推出、升級幅度不大，急用現在買也行。",
    reasons: ["台灣 2026-03-11 開賣，週期進度約五成。", "Bloomberg 報導 iPhone 18e 預計 2027 年春季推出，主要只升級晶片。"],
    signals: [
      { grade: "B", text: "Gurman：iPhone 18e 與數字版 iPhone 18、Air 2 在 2027 年春季推出。", source: "Bloomberg", date: "2026-09-14" },
    ],
    specAdvice: [{ label: "容量", text: "[編輯建議：依台灣售價級距與常見用途填入]" }],
    history: [
      { gen: "iPhone 17e", date: "2026-03-11" },
      { gen: "iPhone 16e", date: "2025-02-28" },
    ],
  },
  {
    slug: "apple-watch",
    name: "Apple Watch Series 12",
    category: "watch",
    icon: "watch",
    releasedTW: "2026-09-18",
    avgDays: 364,
    prev: { name: "Apple Watch Series 11", date: "2025-09-19" },
    next: { name: "Apple Watch Series 13", expected: "2027-09-17", grade: "A", note: "依歷年規律每年 9 月更新，尚無具體報導" },
    priceTW: { from: 13900, config: "最小尺寸 GPS", url: "https://www.apple.com/tw/shop/buy-watch/apple-watch", checked: "2026-10-03" },
    twAvailable: true,
    summary: "剛更新，離下一代最遠。",
    reasons: ["Series 系列近年固定每年 9 月更新。", "台灣 9/18 開賣，至今約兩週。"],
    signals: [{ grade: "A", text: "歷代規律：近年固定 9 月發表、9 月中下旬開賣，多與 iPhone 同場。", source: "本站歷代紀錄", date: "2026-10-02" }],
    specAdvice: [{ label: "行動網路版", text: "[編輯建議：電信 One Number 方案]" }],
    history: [
      { gen: "Series 12", date: "2026-09-18" },
      { gen: "Series 11", date: "2025-09-19" },
      { gen: "Series 10", date: "2024-09-20" },
    ],
  },
  {
    slug: "apple-watch-ultra",
    name: "Apple Watch Ultra 4",
    category: "watch",
    icon: "watch-ultra",
    releasedTW: "2026-09-18",
    avgDays: 485,
    prev: { name: "Apple Watch Ultra 3", date: "2025-09-19" },
    next: { name: "Apple Watch Ultra 5", expected: null, grade: "C", note: "尚無可靠報導；2024 年曾停更一年" },
    priceTW: { from: 27900, config: "49mm GPS + 行動網路", url: "https://www.apple.com/tw/shop/buy-watch/apple-watch-ultra", checked: "2026-10-03" },
    twAvailable: true,
    summary: "剛更新，離下一代最遠。",
    reasons: ["台灣 9/18 與美國同步開賣，至今約兩週。", "Ultra 系列平均約 16 個月更新一次（2024 年曾停更）。"],
    signals: [{ grade: "C", text: "爆料者稱 2027 年 Apple Watch 將大改。", source: "9to5Mac", date: "2026-06-30" }],
    specAdvice: [{ label: "錶帶", text: "[編輯建議：錶帶款式與尺寸]" }],
    history: [
      { gen: "Apple Watch Ultra 4", date: "2026-09-18" },
      { gen: "Apple Watch Ultra 3", date: "2025-09-19" },
      { gen: "Apple Watch Ultra 2", date: "2023-09-22" },
    ],
  },
  {
    slug: "apple-watch-se",
    name: "Apple Watch SE 3",
    category: "watch",
    icon: "watch",
    releasedTW: "2025-09-19",
    avgDays: 914,
    prev: { name: "Apple Watch SE（第 2 代）", date: "2022-09-16" },
    next: { name: "Apple Watch SE（第 4 代）", expected: null, grade: "C", note: "今年沒有新款 SE，下一代時程不明" },
    priceTW: { from: 7900, config: "最小尺寸 GPS", url: "https://www.apple.com/tw/shop/buy-watch/apple-watch-se", checked: "2026-10-03" },
    twAvailable: true,
    summary: "今年沒有新款 SE，下一代最快也要明年以後，需要入門款手錶現在買不太會吃虧。",
    reasons: ["2026 年秋季只更新 Series 12 與 Ultra 4，沒有 SE。", "SE 歷代改款間隔約 2–3 年。"],
    signals: [
      { grade: "B", text: "Gurman：尚未聽說 2026 年有新 Apple Watch SE。", source: "Bloomberg／Macworld", date: "2026-07-27" },
    ],
    specAdvice: [{ label: "尺寸", text: "[編輯建議：40mm 與 44mm]" }],
    history: [
      { gen: "Apple Watch SE 3", date: "2025-09-19" },
      { gen: "Apple Watch SE（第 2 代）", date: "2022-09-16" },
      { gen: "Apple Watch SE（第 1 代）", date: "2020-09-23" },
    ],
  },
  {
    slug: "vision-pro",
    name: "Vision Pro（M5）",
    category: "vision",
    icon: "vision",
    releasedTW: "2025-11-28",
    avgDays: 628,
    prev: { name: "Vision Pro（第一代）", date: "2024-12-17" },
    next: { name: "新一代 Vision Pro", expected: null, grade: "C", note: "據報開發處於維生狀態，最快 2028 年底才可能推出" },
    priceTW: { from: 129900, config: "256GB", variants: [{ label: "512GB", price: 136900 }, { label: "1TB", price: 147400 }], url: "https://www.apple.com/tw/shop/buy-vision/apple-vision-pro", checked: "2026-10-03" },
    twAvailable: true,
    summary: "台灣已開賣，週期中段；下一代前景不明，有需要就買。",
    reasons: ["M5 版 2025-11-28 在台灣開賣。", "週期進度約五成；據報下一代開發已大幅縮減，短期內不會有新款。"],
    signals: [
      { grade: "C", text: "Bloomberg 報導 Apple 評估四種改版 Vision Pro 概念，最快 2028 年底推出，但開發處於維生狀態、不保證推出。", source: "Bloomberg／MacRumors", date: "2026-09-28" },
      { grade: "B", text: "平價版 Vision Air 已於 2025 年喊停，Vision 團隊 2026 年 8 月裁員。", source: "MacRumors", date: "2026-08-21" },
    ],
    specAdvice: [{ label: "購買前", text: "[編輯建議：直營店預約試戴、視力矯正鏡片]" }],
    history: [
      { gen: "Vision Pro（M5）", date: "2025-11-28" },
      { gen: "Vision Pro（第一代）", date: "2024-12-17" },
    ],
  },
  {
    slug: "airpods",
    name: "AirPods 5",
    category: "airpods",
    icon: "airpods",
    releasedTW: "2026-09-18",
    avgDays: 894,
    prev: { name: "AirPods 4", date: "2024-11-12" },
    next: { name: "AirPods 6", expected: null, grade: null, note: "尚無訊號" },
    priceTW: { from: 4490, config: "AirPods 5", variants: [{ label: "配備無線充電盒", price: 5190 }], url: "https://www.apple.com/tw/shop/buy-airpods/airpods-4", checked: "2026-10-03" },
    twAvailable: true,
    summary: "剛更新，離下一代最遠。",
    reasons: ["台灣 9/18 開賣，至今約兩週。", "標準版 AirPods 平均兩年多才更新。"],
    signals: [],
    specAdvice: [{ label: "版本", text: "[編輯建議：是否選主動降噪版]" }],
    history: [
      { gen: "AirPods 5", date: "2026-09-18" },
      { gen: "AirPods 4", date: "2024-11-12" },
      { gen: "AirPods（第 3 代）", date: "2021-12-20" },
    ],
  },
  {
    slug: "airpods-pro",
    name: "AirPods Pro 3",
    category: "airpods",
    icon: "airpods-pro",
    releasedTW: "2025-10-31",
    avgDays: 1076,
    prev: { name: "AirPods Pro 2", date: "2022-11-07" },
    next: { name: "AirPods Pro（鏡頭版）", expected: "2027-09-15", grade: "B", note: "Bloomberg 報導鏡頭版延到 2027 年秋季；日期為推估" },
    priceTW: { from: 7490, config: "AirPods Pro 3", url: "https://www.apple.com/tw/shop/buy-airpods/airpods-pro-3", checked: "2026-10-03" },
    twAvailable: true,
    summary: "週期約三成，下一代鏡頭版延到 2027 年秋季，有需要就買。",
    reasons: ["台灣 2025-10-31 開賣，週期進度約三成。", "Bloomberg 報導有鏡頭的 AirPods Pro 已從 2026 年規劃移除，延到 2027 年。"],
    signals: [
      { grade: "B", text: "Gurman：有鏡頭的 AirPods Pro 已從 2026 年規劃移除，延到 2027 年。", source: "Bloomberg／MacRumors", date: "2026-08-19" },
    ],
    specAdvice: [{ label: "版本", text: "[編輯建議：與 AirPods 5 主動降噪版的差異]" }],
    history: [
      { gen: "AirPods Pro 3", date: "2025-10-31" },
      { gen: "AirPods Pro 2", date: "2022-11-07" },
      { gen: "AirPods Pro", date: "2019-12-30" },
    ],
  },
  {
    slug: "airpods-max",
    name: "AirPods Max 2",
    category: "airpods",
    icon: "headphones",
    releasedTW: "2026-04-23",
    avgDays: 1933,
    prev: { name: "AirPods Max", date: "2020-12-14" },
    next: { name: "AirPods Max 3", expected: null, grade: "C", note: "只有郭明錤 2025 年預測更輕的新款 2027 年量產" },
    priceTW: { from: 17990, config: "AirPods Max 2", url: "https://www.apple.com/tw/shop/buy-airpods/airpods-max-2", checked: "2026-10-03" },
    twAvailable: true,
    summary: "AirPods Max 2 今年春天才推出，下一代沒有可靠消息，現在買是好時機。",
    reasons: ["台灣 2026-04-23 開賣，升級 H2 晶片。", "上一次大改款隔了五年多。"],
    signals: [
      { grade: "C", text: "郭明錤：更輕的 AirPods Max 預計 2027 年量產（Max 2 推出前的說法）。", source: "MacRumors", date: "2025-05-19" },
    ],
    specAdvice: [{ label: "顏色", text: "[編輯建議：顏色與配件]" }],
    history: [
      { gen: "AirPods Max 2", date: "2026-04-23" },
      { gen: "AirPods Max", date: "2020-12-14" },
    ],
  },
  {
    slug: "apple-tv",
    name: "Apple TV 4K（第 3 代）",
    category: "tvhome",
    icon: "appletv",
    releasedTW: "2022-12-07",
    avgDays: 934,
    prev: { name: "Apple TV 4K（第 2 代）", date: "2021-06-10" },
    next: { name: "Apple TV 4K（第 4 代）", expected: "2026-10-13", grade: "A", note: "新款已在 Apple 程式碼外洩；10/13 為 Bloomberg 報導的預期發表日，未經官方確認" },
    priceTW: { from: 6900, config: "Wi-Fi 64GB", variants: [{ label: "Wi-Fi + 乙太網路 128GB", price: 8500 }], url: "https://www.apple.com/tw/shop/buy-tv/apple-tv-4k", checked: "2026-10-03" },
    twAvailable: true,
    summary: "新款已外洩、傳聞 10/13 發表，先別買。",
    reasons: ["「Apple TV 4K（第 4 代）」已出現在 Apple 程式碼（A 級訊號）。", "Bloomberg 報導 10/13 與 HomePod mini、家庭中樞同場發表。"],
    signals: [
      { grade: "B", text: "audioOS 與 macOS 27.2 測試版出現四顆 HomePod 環繞音效的程式碼與圖示，傳為新 Apple TV 4K 功能。", source: "MacRumors", date: "2026-10-06" },
      { grade: "A", text: "tvOS 27.2 測試版 3 程式碼加入 Apple Intelligence 設定與 Siri 訊息介面，為支援 Siri AI 的新 Apple TV 鋪路。", source: "MacRumors（程式碼分析）", date: "2026-10-05" },
      { grade: "B", text: "Gurman：Apple 計畫 10/13 舉辦發表活動，推出家庭中樞、新 HomePod mini 與 Apple TV 4K。", source: "Bloomberg Power On／MacRumors", date: "2026-10-04" },
      { grade: "A", text: "「Apple TV 4K（第 4 代）」圖檔出現在 Apple 程式碼，型號 AppleTV18,1 已於 9/8 被發現。", source: "MacRumors（程式碼分析）", date: "2026-09-25" },
      { grade: "B", text: "Bloomberg 報導新款 Apple TV 將於 10/13 與 HomePod mini、家庭中樞同場發表。", source: "Bloomberg／9to5Mac", date: "2026-09-30" },
    ],
    specAdvice: [{ label: "容量", text: "[編輯建議：64GB 與 128GB 差異]" }],
    history: [
      { gen: "Apple TV 4K（第 3 代）", date: "2022-12-07" },
      { gen: "Apple TV 4K（第 2 代）", date: "2021-06-10" },
      { gen: "Apple TV 4K（第 1 代）", date: "2017-09-22" }, // 美國日期，台灣開賣日查無
    ],
  },
  {
    slug: "homepod",
    name: "HomePod（第 2 代）",
    category: "tvhome",
    icon: "homepod",
    releasedTW: "2023-03-21",
    avgDays: 1820,
    prev: { name: "HomePod（第一代）", date: "2019-08-23" },
    next: { name: "HomePod（第 3 代）", expected: null, grade: "B", note: "新款仍在計畫中，Bloomberg 稱不在 10/13 發表名單" },
    priceTW: { from: 10990, config: "HomePod", url: "https://www.apple.com/tw/shop/buy-homepod/homepod", checked: "2026-10-03" },
    twAvailable: true,
    override: { verdict: "care", reason: "週期進度約七成，且多方報導新款仍在開發中，雖無明確時間仍列為小心。" },
    summary: "接近週期尾聲，新款仍在計畫中，急用再買。",
    reasons: ["上市已超過三年半。", "Bloomberg 報導新款仍在開發，但不在 10/13 發表、時間未定。"],
    signals: [
      { grade: "B", text: "Bloomberg 報導 Apple 仍在開發新款 HomePod（新晶片支援 Siri AI），時間未定。", source: "Bloomberg／9to5Mac", date: "2026-08-15" },
      { grade: "B", text: "Bloomberg：全尺寸 HomePod 不在 10/13 發表名單，Apple 仍打算日後更新。", source: "Bloomberg／9to5Mac", date: "2026-09-30" },
    ],
    specAdvice: [{ label: "台灣功能", text: "[編輯建議：Siri 中文與服務可用性]" }],
    history: [
      { gen: "HomePod（第 2 代）", date: "2023-03-21" },
      { gen: "HomePod（第一代）", date: "2019-08-23" },
    ],
  },
  {
    slug: "homepod-mini",
    name: "HomePod mini",
    category: "tvhome",
    icon: "homepod-mini",
    releasedTW: "2020-11-16",
    avgDays: null,
    prev: null,
    next: { name: "HomePod mini（第 2 代）", expected: "2026-10-13", grade: "B", note: "Bloomberg 報導 10/13 與 Apple TV、家庭中樞同場推出" },
    priceTW: { from: 3990, config: "HomePod mini", url: "https://www.apple.com/tw/shop/buy-homepod/homepod-mini", checked: "2026-10-03" },
    twAvailable: true,
    summary: "第一代已賣近 6 年，第 2 代傳 10/13 推出，先等一下。",
    reasons: ["現行款是 2020 年的第一代，台灣 2020-11-16 開賣。", "Bloomberg 報導第 2 代將於 10/13 推出（B 級訊號）。"],
    signals: [
      { grade: "B", text: "HomePod mini 在美國、英國、日本等地官網出貨等待拉長到最多 8 週，部分顏色缺貨，常見於換代前。", source: "MacRumors", date: "2026-10-06" },
      { grade: "B", text: "Gurman：Apple 計畫 10/13 舉辦發表活動，推出家庭中樞、新 HomePod mini 與 Apple TV 4K。", source: "Bloomberg Power On／MacRumors", date: "2026-10-04" },
      { grade: "B", text: "Gurman：Apple 將在 10/13 推出新 HomePod mini、家庭中樞與 Apple TV。", source: "Bloomberg／MacRumors", date: "2026-09-30" },
      { grade: "B", text: "Gurman：家庭中樞與更新的 HomePod mini 最快 10 月推出。", source: "Bloomberg／MacRumors", date: "2026-09-21" },
    ],
    specAdvice: [{ label: "顏色", text: "[編輯建議：顏色與立體聲配對]" }],
    history: [{ gen: "HomePod mini", date: "2020-11-16" }],
  },
  {
    slug: "airtag",
    name: "AirTag（第 2 代）",
    category: "accessories",
    icon: "airtag",
    releasedTW: "2026-01-26",
    avgDays: 1734,
    prev: { name: "AirTag（第一代）", date: "2021-05-24" },
    next: { name: "AirTag（第 3 代）", expected: null, grade: null, note: "尚無訊號" },
    priceTW: { from: 990, config: "單入", variants: [{ label: "四入", price: 3390 }], url: "https://www.apple.com/tw/shop/buy-airtag/airtag", checked: "2026-10-03" },
    twAvailable: true,
    summary: "第二代剛推出，可以買。",
    reasons: ["上一代相隔近五年才更新。"],
    signals: [],
    specAdvice: [{ label: "組合", text: "[編輯建議：四入組價差]" }],
    history: [
      { gen: "AirTag（第 2 代）", date: "2026-01-26" },
      { gen: "AirTag（第一代）", date: "2021-05-24" },
    ],
  },
];

export function formatNT(n: number): string {
  return "NT$" + n.toLocaleString("en-US");
}

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}
